name: PHP CLI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *" # 1 AM UTC on 1st day of month
  push:
    paths:
      - .trigger
      - .github/workflows/cli.yml
      - cli/**
    branches: [ "master" ]

env:
  GLOBAL_NODE_VERSION: 14

jobs:
  cli:
    name: Build PHP images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - from: "7.4-cli-bullseye"
            tag: "7.4"
          - from: "8.0-cli-bullseye"
            tag: "8.0"
          - from: "8.1-cli-bullseye"
            tag: "8.1"
          - from: "8.2-cli-buster"
            tag: "8.2"

    steps:

      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: cli
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          build-args: PHP_VERSION=${{ matrix.version.from }} NODE_MAJOR=${{env.GLOBAL_NODE_VERSION}}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/epartment/magento-2-ci:${{ matrix.version.tag }}
