name: PHP CLI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *" # 1 AM UTC on 1st day of month
  push:
    paths:
      - .trigger
      - .github/workflows/cli.yml
      - cli/**
    branches: [ "master" ]

env:
  GLOBAL_NODE_VERSION: 18

jobs:
  cli:
    name: Build PHP images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:


    steps:

      - name: Set up Actions
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: cli
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          build-args: |
            "PHP_VERSION=${{ matrix.version.from }}"
            "NODE_MAJOR=${{ env.GLOBAL_NODE_VERSION }}"
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/epartment/magento-2-ci:${{ matrix.version.tag }}
