name: PHP CLI
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - .trigger
      - .github/workflows/cli.yml
      - cli/**
    branches: [ "master" ]

jobs:
  cli:
    name: Build PHP images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - from: "7.2-cli-buster"
            tag: "7.2"
          - from: "7.3-cli-bullseye"
            tag: "7.3"
          - from: "7.4-cli-bullseye"
            tag: "7.4"
          - from: "8.0-cli-bullseye"
            tag: "8.0"
          - from: "8.1-cli-bullseye"
            tag: "8.1"
          - from: "8.2-rc-cli-buster"
            tag: "8.2"

    steps:
      - run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }}

      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v2
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version.from }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/epartment/magento-2-ci:${{ matrix.version.tag }}
