name: Gitlab CI Deployer
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 1 * *"   # 01 AM on first day of the month
  pull_request:
  push:
    paths:
      - .trigger
      - deployer/Dockerfile
      - .github/workflows/imageci-deployer.yml
      - .github/workflows/php-matrix/deployer-generator.php
      - .github/workflows/php-matrix/constants.php
jobs:
  deployer-matrix:
    name: Generate Base Deployer-Node Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - id: matrix
        run: |
          php .github/workflows/php-matrix/deployer-generator.php >> $GITHUB_OUTPUT
      - run: echo "Matrix:\n";echo '${{ steps.matrix.outputs.matrix }}'

  ci-deployer:
    name: Gitlab CI Deployer + Node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    needs: deployer-matrix
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/master' && 6 || 0 }}
      matrix: ${{fromJson(needs.deployer-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v5
        with:
          context: deployer
          platforms: linux/amd64,linux/arm64
          build-args: |
            DEPLOYER_VERSION=${{ matrix.deployer_version }}
            NODE_VERSION=${{ matrix.node_version }}
            OS_RELEASE=${{ matrix.node_os_release }}

          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/${{ github.repository_owner }}/gitlab-ci:deployer-${{ matrix.deployer_version }}-node${{ matrix.node_version }}
          cache-from: type=registry,ref=docker.io/epartment/gitlab-ci:deployer-${{ matrix.deployer_version }}-node${{ matrix.node_version }}-buildcache
          cache-to: type=registry,ref=docker.io/epartment/gitlab-ci:deployer-${{ matrix.deployer_version }}-node${{ matrix.node_version }}-buildcache,mode=max

      - uses: docker/build-push-action@v5
        if: ${{ matrix.latest }}
        with:
          context: deployer
          platforms: linux/amd64,linux/arm64
          build-args: |
            DEPLOYER_VERSION=${{ matrix.deployer_version }}
            NODE_VERSION=${{ matrix.node_version }}
            OS_RELEASE=${{ matrix.node_os_release }}

          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/${{ github.repository_owner }}/gitlab-ci:deployer-latest-nodelatest
          cache-from: type=registry,ref=docker.io/epartment/gitlab-ci:deployer-latest-nodelatest-buildcache
          cache-to: type=registry,ref=docker.io/epartment/gitlab-ci:deployer-latest-nodelatest-buildcache,mode=max
